version: '3'

services:
  docker_registry:
    container_name: 'registry'
    image: registry:2
    restart: always
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:4000
    volumes:
      - registry_data:/var/lib/registry
    ports:
      - 4000:4000
    network_mode: bridge

volumes:
  registry_data:
