- name: Add Docker gpg key to system
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    validate_certs: false

- name: Add docker repository
  apt_repository:
    filename: docker
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_facts.distribution_release}} stable"
    update_cache: true
    validate_certs: false

- name: Apt update and install docker and other dependencies
  apt:
    allow_unauthenticated: true
    force_apt_get: true
    install_recommends: true
    name: "{{ package }}"
    state: latest
    update_cache: true
  loop: ["python","python-pip","screen","htop","wget","nmap","curl","at","vim","apt-transport-https","ca-certificates","gnupg-agent","software-properties-common","docker-ce","docker-ce-cli","containerd.io"]
  loop_control:
    loop_var: package

- name: Apt clean and remove unnecessary dependencies
  apt:
    autoclean: true
    autoremove: true

